### ISSUE TITLE
Double call to callback from getbulk under certain circumstances (not as #38)

### ISSUE THREAD

**Issue by unchained-za** [markabrahams/node-net-snmp#95] opened 2020-06-03 11:57 UTC
In this specific case I call getbulk with 4 OIDs of which 2 overlap with getbulk. I first used the default (20) maxRepititions, then specifically with 10 and 20 (and others). With anything greater than 18 the problem starts.
It is a Cisco router and the OIDs are:
["1.3.6.1.2.1.1.5.0", "1.3.6.1.2.1.1.9.0", "1.3.6.1.2.1.2.2.1.10.7", "1.3.6.1.2.1.2.2.1.17.9"]
Note the first and second ones.

The callback gets called first with an error:
ERROR, ResponseInvalidError: Varbind count in response '73' is not a multiple of repeaters '4' plus non-repeaters '0' in request
Then with an empty {} result.

I picked it up because I closed the session after the error and then got an exception due to the closed socket, so I realised the callback must be called again, hence adding some debugs.

Net-SNMP snmpbulkget does however work:
$ snmpbulkget -v 2c -c xxx -On -Cr20 10.15.0.50 1.3.6.1.2.1.1.5.0 1.3.6.1.2.1.1.9.0 1.3.6.1.2.1.2.2.1.10.7 1.3.6.1.2.1.2.2.1.17.9 | wc -l
**73**
$

$ snmpbulkget -v 2c -c xxx -On -Cr20 10.15.0.50 1.3.6.1.2.1.1.5.0 1.3.6.1.2.1.1.9.0 1.3.6.1.2.1.2.2.1.10.7 1.3.6.1.2.1.2.2.1.17.9
.1.3.6.1.2.1.1.6.0 = STRING: "XXX CT office, Bellville, Western Cape, South Africa, ZA"
.1.3.6.1.2.1.2.1.0 = INTEGER: 18
.1.3.6.1.2.1.2.2.1.10.8 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.10 = Counter32: 1956709
.1.3.6.1.2.1.1.7.0 = INTEGER: 78
.1.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.10.9 = Counter32: 869948204
.1.3.6.1.2.1.2.2.1.17.11 = Counter32: 0
.1.3.6.1.2.1.1.8.0 = Timeticks: (0) 0:00:00.00
.1.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.10.10 = Counter32: 1489061750
.1.3.6.1.2.1.2.2.1.17.12 = Counter32: 0
.1.3.6.1.2.1.2.1.0 = INTEGER: 18
.1.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
.1.3.6.1.2.1.2.2.1.10.11 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.13 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.1.4 = INTEGER: 4
.1.3.6.1.2.1.2.2.1.10.12 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.14 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.1.5 = INTEGER: 5
.1.3.6.1.2.1.2.2.1.10.13 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.15 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
.1.3.6.1.2.1.2.2.1.1.6 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.10.14 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.16 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.4 = INTEGER: 4
.1.3.6.1.2.1.2.2.1.1.7 = INTEGER: 7
.1.3.6.1.2.1.2.2.1.10.15 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.17 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.5 = INTEGER: 5
.1.3.6.1.2.1.2.2.1.1.8 = INTEGER: 8
.1.3.6.1.2.1.2.2.1.10.16 = Counter32: 0
.1.3.6.1.2.1.2.2.1.17.18 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.6 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.1.9 = INTEGER: 9
.1.3.6.1.2.1.2.2.1.10.17 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.7 = INTEGER: 7
.1.3.6.1.2.1.2.2.1.1.10 = INTEGER: 10
.1.3.6.1.2.1.2.2.1.10.18 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.8 = INTEGER: 8
.1.3.6.1.2.1.2.2.1.1.11 = INTEGER: 11
.1.3.6.1.2.1.2.2.1.11.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.9 = INTEGER: 9
.1.3.6.1.2.1.2.2.1.1.12 = INTEGER: 12
.1.3.6.1.2.1.2.2.1.11.2 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.10 = INTEGER: 10
.1.3.6.1.2.1.2.2.1.1.13 = INTEGER: 13
.1.3.6.1.2.1.2.2.1.11.3 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.11 = INTEGER: 11
.1.3.6.1.2.1.2.2.1.1.14 = INTEGER: 14
.1.3.6.1.2.1.2.2.1.11.4 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.12 = INTEGER: 12
.1.3.6.1.2.1.2.2.1.1.15 = INTEGER: 15
.1.3.6.1.2.1.2.2.1.11.5 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.7 = Counter32: 13171687
.1.3.6.1.2.1.2.2.1.1.13 = INTEGER: 13
.1.3.6.1.2.1.2.2.1.1.16 = INTEGER: 16
.1.3.6.1.2.1.2.2.1.11.6 = Counter32: 0
.1.3.6.1.2.1.2.2.1.19.8 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.14 = INTEGER: 14
.1.3.6.1.2.1.2.2.1.1.17 = INTEGER: 17
.1.3.6.1.2.1.2.2.1.11.7 = Counter32: 123921673
.1.3.6.1.2.1.2.2.1.19.9 = Counter32: 0
.1.3.6.1.2.1.2.2.1.1.15 = INTEGER: 15
$

**Comment by unchained-za** [comment] 2020-06-03 14:06
More info: in this instance the Net-SNMP snmpbulkget actually returns an incomplete result without any error indication. Up to maxRepetitons of 18 it is correct (72), thereafter it only returns 73, regardless of the size of maxRepetitions. I don't know what the limitations on bulkget are or whether it is agent or client dependent, but the behaviour of both are arguably wrong. The Net-SNMP snmpbulkget doesn't give any indication that the result may be incomplete and the node getbulk first returns an error, then an empty result. Neither gives an indication of how many entries should have been returned. For the time being I'll check for the specific error and not close the session on receipt of the error, only after the empty result.
An increase in the number of OIDs means a decrease in the number of maxRepetitions and of the number of returned values.

**Comment by markabrahams** [comment] 2020-07-07 16:49
Hi @unchained-za - if you're able to attach some packet captures of the Net-SNMP and node net-snmp library, that would help to pinpoint the problem.  Also code for a minimal reproduction would help.

**Comment by unchained-za** [comment] 2020-07-07 20:36
Hi, I am working on the module again, but I'll need some time to get to that problem again, under quite some pressure at the moment.

**Comment by mvduin** [comment] 2022-06-04 01:23
Yeah, when that error gets triggered you get a double callback because there's no `return` after that error, but the entire error is bogus anyway. See #205 for a fix.

**Comment by markabrahams** [comment] 2022-06-05 10:26
Have merged #205 which resolves this issue.  Thanks @mvduin for the fix!

**Closed by markabrahams** 2022-06-05 10:26 UTC
Labels: insufficient information
